# Generated by Django 4.2.17 on 2025-01-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0002_alter_citation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='status',
            field=models.CharField(choices=[('a', 'available'), ('u', 'unavailable'), ('r', 'redirect'), ('x', 'auto-validated from previous draft of opinion')], default='a', max_length=1),
        ),
    ]
